### ISSUE TITLE
Control dataset access

### ISSUE THREAD

**Issue by tdigangi** [terraform-google-modules/terraform-google-bigquery#12]
All users that need to consume the data set need at minimum dataset viewer. Would best to have an array of users and be able to access.

**Comment by aaron-lane** [comment]
@tdigangi would this be fixed by #38?

**Comment by tdigangi** [comment]
Yes, upon merge of PR [#38](https://github.com/terraform-google-modules/terraform-google-bigquery/pull/38) we can close this issue.

**Comment by dharamsk** [comment]
Was it intentional to use `list` instead of `set` for the access resource? A list expects ordered values, but the values are not ordered, so it shows all items in the list being removed and re-added, effectively hiding the true changes. In our case, we have a large number (dozens) of individual users to grant dataset access to, resulting in an unreadable 400 line diff for a single add/remove.
